using Cinema;
using Cinema.Enums;
using System.Collections.Generic;
using System;
using Microsoft.Extensions.DependencyInjection;

var zoneMultipliers = new Dictionary<TicketZone, decimal>
{
    { TicketZone.Low, 0.9m },
    { TicketZone.Mid, 1.0m },
    { TicketZone.Upper, 1.2m }
};

var typeMultipliers = new Dictionary<TicketType, decimal>
{
    { TicketType.TwoD, 0.5m },
    { TicketType.ThreeD, 1.0m }
};

var services = new ServiceCollection();
services.AddSingleton<ITicketPricer>(sp =>
    new TicketPricer(zoneMultipliers, typeMultipliers)
);

var provider = services.BuildServiceProvider();
var pricer = provider.GetRequiredService<ITicketPricer>();

// all below generated by chat
// Sample data
var movie1 = new Movie("Inception", pricer, 30m);
var movie2 = new Movie("The Matrix", pricer, 28m);

// Sell some tickets for movie1
movie1.SellTicket(new Ticket(new Seat(5, 2), movie1, TicketType.TwoD));   // Row 2 => Low
movie1.SellTicket(new Ticket(new Seat(3, 4), movie1, TicketType.TwoD)); // Row 4 => Mid
movie1.SellTicket(new Ticket(new Seat(7, 9), movie1, TicketType.ThreeD));  // Row 9 => Upper

// Sell some tickets for movie2
movie2.SellTicket(new Ticket(new Seat(2, 1), movie2, TicketType.ThreeD));
movie2.SellTicket(new Ticket(new Seat(10, 6), movie2, TicketType.TwoD));
movie2.SellTicket(new Ticket(new Seat(14, 8), movie2, TicketType.TwoD));

// Compute revenues
var r1 = movie1.GetRevenue();
var r2 = movie2.GetRevenue();

// Output
Console.WriteLine($"Revenue for {movie1.Title}: {r1:C}");
Console.WriteLine($"Revenue for {movie2.Title}: {r2:C}");

// Verify individual ticket pricing sample
var probe = new Ticket(new Seat(1, 7), movie1, TicketType.TwoD); // Row 7 => Mid
Console.WriteLine($"Probe ticket price (movie1, Mid row, Student): {pricer.GetPrice(probe):C}");